version: "3"

services:

  metrics-collector:
    image: "metrics-collector:latest"
    container_name: metrics-collector
    deploy:
      placement:
        constraints:
          - node.labels.role==manager
    networks:
      - spark-network
    depends_on:
      - generator
      - mariadb

  mariadb:
    container_name: spark-mariadb
    image: mariadb:10.4
    command: --character-set-server=utf8 --lower_case_table_names
    volumes:
      - ./logs/db/init.sql:/docker-entrypoint-initdb.d/1.sql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=spark
      - MYSQL_DATABASE=spark
      - MYSQL_USER=spark
      - MYSQL_PASSWORD=spark
    networks:
      - spark-network

  spark-master:
    image: "bitnami/spark:3.2.0"
    container_name: spark_master
    ports:
      - "8080:8080"
    environment:
      - SPARK_MODE=master # default
    volumes:
      - ./logs/spark/metrics.properties:/opt/bitnami/spark/conf/metrics.properties
    deploy:
      placement:
        constraints:
          - node.labels.role==master
    networks:
      - spark-network

  spark-worker-1:
    image: "bitnami/spark:3.2.0"
    container_name: spark_worker_1
    ports:
      - "8081:8081"
    environment:
      - SPARK_MODE=worker
      - SPARK_WORKER_CORES=2
      - SPARK_WORKER_MEMORY=3G
    volumes:
      - ./logs/spark/metrics.properties:/opt/bitnami/spark/conf/metrics.properties
    deploy:
      placement:
        constraints:
          - node.labels.role==worker
      replicas: 1
    networks:
      - spark-network

  spark-worker-2:
    image: "bitnami/spark:3.2.0"
    container_name: spark_worker_2
    ports:
      - "8082:8082"
    environment:
      - SPARK_MODE=worker
      - SPARK_WORKER_CORES=2
      - SPARK_WORKER_MEMORY=3G
    volumes:
      - ./logs/spark/metrics.properties:/opt/bitnami/spark/conf/metrics.properties
    deploy:
      placement:
        constraints:
          - node.labels.role==worker
      replicas: 1
    networks:
      - spark-network

  spark-worker-3:
    image: "bitnami/spark:3.2.0"
    container_name: spark_worker_3
    ports:
      - "8083:8083"
    environment:
      - SPARK_MODE=worker
      - SPARK_WORKER_CORES=2
      - SPARK_WORKER_MEMORY=3G
    volumes:
      - ./logs/spark/metrics.properties:/opt/bitnami/spark/conf/metrics.properties
    deploy:
      placement:
        constraints:
          - node.labels.role==worker
      replicas: 1
    networks:
      - spark-network

  driver:
    image: "driver:latest"
    container_name: spark_driver
    ports:
      - "4040:4040"
    user: root # This fixes KerberosAuthException during spark-submit: https://issueexplorer.com/issue/bitnami/bitnami-docker-spark/27
    deploy:
      placement:
        constraints:
          - node.labels.role==manager
    networks:
      - spark-network
    volumes:
      - ./logs/spark/metrics.properties:/opt/bitnami/spark/conf/metrics.properties
      - ./logs/checkpoint:/opt/bitnami/checkpoint # structured streaming will save checkpoints in this location
    depends_on:
      - spark-master
      - spark-worker-1
      - spark-worker-2
      - spark-worker-3
      - kafka
  generator:
    image: "generator:latest"
    container_name: generator
    ports:
      - "8091:8080"
    environment:
      - BOOTSTRAP_KAFKA_SERVER=kafka:9092
    deploy:
      placement:
        constraints:
          - node.labels.role==manager
    networks:
      - spark-network
    depends_on:
      - driver

  kafka:
    image: "wurstmeister/kafka:latest"
    container_name: kafka
    ports:
      - "29092:29092"
      - "7071:7071"
    environment:
      - KAFKA_CREATE_TOPICS="output:3:1" # topic_name:number_of_partitions_number_of_replicas
      - KAFKA_BROKER_ID=1
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_LISTENERS=HOST_INTERNAL://:29092, DOCKER_INTERNAL://kafka:9092 # Makes Kafka broker accessible in the docker overlay network (no external): https://rmoff.net/2018/08/02/kafka-listeners-explained/
      - KAFKA_ADVERTISED_LISTENERS=HOST_INTERNAL://localhost:29092, DOCKER_INTERNAL://kafka:9092
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=HOST_INTERNAL:PLAINTEXT, DOCKER_INTERNAL:PLAINTEXT
      - KAFKA_INTER_BROKER_LISTENER_NAME=DOCKER_INTERNAL
#      - KAFKA_OPTS=-javaagent:/usr/app/jmx_prometheus_javaagent.jar=7071:/usr/app/prom-jmx-agent-config.yml
    deploy:
      placement:
        constraints:
          - node.labels.role==manager
    networks:
      - spark-network
    volumes:
#      - ./logs/jmx/jmx_prometheus_javaagent-0.16.1.jar:/usr/app/jmx_prometheus_javaagent.jar
#      - ./logs/kafka/prom-jmx-agent-config.yml:/usr/app/prom-jmx-agent-config.yml
      - ./logs/kafka:/kafka # Keep this volume if you don't want to run into device-out-of-memory error. Otherwise you would need either to delete Kafka topic's data via Producer API call, or navigate to docker's /var/lib/docker/volumes/ and do it manually (instructions: https://stackoverflow.com/questions/38532483/where-is-var-lib-docker-on-mac-os-x)
    depends_on:
      - zookeeper

  grafana:
    image: "preconfigured-grafana:latest"
    container_name: spark_grafana
    volumes:
      - ./logs/grafana/data:/opt/bitnami/grafana/data
    ports:
      - "3000:3000"
    networks:
      - spark-network

  prometheus:
    image: bitnami/prometheus
    container_name: prometheus
    volumes:
      - ./logs/prometheus/conf:/opt/bitnami/prometheus/conf
      - ./logs/prometheus/data:/opt/bitnami/prometheus/data
    ports:
      - "9090:9090"
    depends_on:
      - kafka
    networks:
      - spark-network

  zookeeper:
    image: "zookeeper:latest" # This image is configured with volumes at /data and /datalog to hold the Zookeeper in-memory database snapshots and the transaction log of updates to the database
    container_name: zookeeper
    ports:
      - "2181:2181"
    restart: always # Since the Zookeeper "fails fast" it's better to always restart it
    environment:
      - ZOO_LOG4J_PROP="INFO,ROLLINGFILE" # Redirects logging to /logs/zookeeper.log, the image already has a volume in /logs
    deploy:
      placement:
        constraints:
          - node.labels.role==manager
    networks:
      - spark-network

  #gremlin:
  #  image: "gremlin/gremlin:latest"
  #  container_name: gremlin
  #  ports:
  #    - ":"
  #  environment:
  #    - GREMLIN_TEAM_ID=8882f35b-8baa-4265-82f3-5b8baa82659b
  #    - GREMLIN_TEAM_SECRET=6e06d523-16ec-4c00-86d5-2316ecec00f0
  #  deploy:
  #    placement:
  #      constraints:
  #        - node.labels.role==manager
  #  networks:
  #    - spark-network

networks:
  spark-network:
    driver: overlay