global:
  scrape_interval: 15s
scrape_configs:
  - job_name: 'spark-master'
    scrape_interval: 1s
    static_configs:
      - targets: ['spark_master:8080']
    metrics_path: "/metrics/master/prometheus"
  - job_name: 'spark-worker-1'
    scrape_interval: 1s
    static_configs:
      - targets: ['spark_worker_1:8081']
    metrics_path: "/metrics/prometheus"
  - job_name: 'spark-worker-2'
    scrape_interval: 1s
    static_configs:
      - targets: ['spark_worker_2:8082']
    metrics_path: "/metrics/prometheus"
  - job_name: 'spark-worker-3'
    scrape_interval: 1s
    static_configs:
      - targets: ['spark_worker_3:8083']
    metrics_path: "/metrics/prometheus"
  - job_name: 'spark-driver'
    scrape_interval: 1s
    static_configs:
      - targets: ['driver:4040']
    metrics_path: "/metrics/prometheus"
  - job_name: 'spark-executor'
    scrape_interval: 1s
    static_configs:
      - targets: ['driver:4040']
    metrics_path: "/metrics/executors/prometheus"
  - job_name: 'kafka'
    scrape_interval: 1s
    static_configs:
      - targets: ['prometheus-kafka:9308']
  - job_name: 'kafka-jmx'
    scrape_interval: 1s
    static_configs:
      - targets: ['kafka:7071']
  - job_name: 'grafana'
    scrape_interval: 1s
    static_configs:
      - targets: ['spark_grafana:3000']
  - job_name: 'node-exporter-1'
    scrape_interval: 1s
    static_configs:
      - targets: ['node-exporter-1:9100']
  - job_name: 'node-exporter-2'
    scrape_interval: 1s
    static_configs:
      - targets: [ 'node-exporter-2:9100' ]
  - job_name: 'node-exporter-3'
    scrape_interval: 1s
    static_configs:
      - targets: [ 'node-exporter-3:9100' ]
  - job_name: 'node-exporter-4'
    scrape_interval: 1s
    static_configs:
      - targets: [ 'node-exporter-4:9100' ]